import Head from "next/head";
import styles from "../styles/Login.module.css";
import Image from "next/image";
import BackgroundImage from "../public/images/disneyplus-login.png";
import Logo from "../public/images/logo.png";
import Header from "../components/Header";
import { useAuth } from "../context/UserContext";
import { useRouter } from "next/router";
import Home from "./home";
export default function Login() {
  const { currentUser } = useAuth();
  const router = useRouter();
  if (currentUser?.id !== undefined) {
    return <Home />;
  } else {
    return (
      <>
        <Head>
          <title>Disney+ Clone</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* header */}
        <Header />
        {/* body */}
        <div className={styles.container}>
          <div className={styles.imageContainer}>
            <Image
              className={styles.backgroundImage}
              src={BackgroundImage}
              alt="background"
            />
          </div>
          <div className={styles.contents}>
            {/* logo */}
            <div>
              <Image className={styles.logo} src={Logo} alt="logo" />
            </div>
            <div className={styles.description}>
              <h1>+ More than you’d ever imagine</h1>
              <h3>Enter your email to create or restart your subscription.</h3>
              {/* input -button */}
              <div className={styles.formContent}>
                <input type="text" placeholder="Email" />
                <button>CONTINUE</button>
              </div>
              <h3>
                Get 12 months for the price of 10 when you sign up for an annual
                Disney+ subscription, compared to paying monthly.
              </h3>
              <h5>Welcome to Chippendales streaming January 11.</h5>
            </div>
          </div>
        </div>
      </>
    );
  }
}
